/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StateSvr_CONSTANTS_H
#define StateSvr_CONSTANTS_H

#include "StateSvr_types.h"

namespace protruly {

class StateSvrConstants {
 public:
  StateSvrConstants();

};

extern const StateSvrConstants g_StateSvr_constants;

} // namespace

#endif
