/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "StateSvr_constants.h"

namespace protruly {

const StateSvrConstants g_StateSvr_constants;

StateSvrConstants::StateSvrConstants() {
}

} // namespace

